version: '3.4'

services:
  productsservice:
    image: ${DOCKER_REGISTRY-}productsservice
    build:
      context: .
      dockerfile: ProductsService/Dockerfile
    ports:
      - "5000:80"

  ordersservice:
    image: ${DOCKER_REGISTRY-}ordersservice
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    ports:
      - "5001:80"
